class_name GameSession
extends RefCounted
## THE HAND-OFF between the menu and the world scene. Static-only; never instantiated.
##
## WHY A STATIC VAR AND NOT AN AUTOLOAD. `change_scene_to_file()` takes no arguments, so the
## intent to open a particular world has to survive the scene change somewhere. `WorldRoot`
## already uses `static var _instance` for exactly this class of problem, so this matches the
## idiom rather than introducing a second one — and it means no `project.godot` change and no
## global node a headless test has to work around. Tests call `clear()` between cases.
##
## IT IS CONSUMED, NOT READ. `consume()` clears the intent as it returns it, so a second world
## scene entered without going through a menu (a test, a future restart) gets `"none"` and
## builds a default world rather than silently re-loading the last save.

static var _mode: String = "none"
static var _preset: WorldPreset = null
static var _name: String = ""
static var _path: String = ""
static var _seed: int = 0


## `seed_value` is the world's permanent seed, GENERATED BY THE MENU (`new_game_screen.gd`) and
## carried through here. It is deliberately not defaulted: a caller that has not thought about
## the seed would otherwise hand every new world the 0 that the 2026-08-02 ruling exists to
## remove — and 0 is a sentinel elsewhere (`ArrivalQueue._init()` reads it as "randomize").
static func request_new(preset: WorldPreset, world_name: String, path: String, seed_value: int) -> void:
	_mode = "new"
	_preset = preset
	_name = world_name
	_path = path
	_seed = seed_value


static func request_load(path: String) -> void:
	_mode = "load"
	_preset = null
	_name = ""
	_path = path
	# A loaded world's seed comes out of its own file, never from here.
	_seed = 0


## The pending intent, cleared as it is returned.
static func consume() -> Dictionary:
	var out := {"mode": _mode, "preset": _preset, "name": _name, "path": _path, "seed": _seed}
	clear()
	return out


static func clear() -> void:
	_mode = "none"
	_preset = null
	_name = ""
	_path = ""
	_seed = 0
