"""The `.tres` header contract the fidelity audit reads.

The audit compares runtime against source MODULO what the artifact itself declares, which
keeps the reason for an exemption next to the thing it excuses rather than in a script
constant. Same principle as the pipeline's `auto_accepted` stamp: the artifact states what
was decided about it.
"""

from pathlib import Path

SOURCE_KEY = "; Source:"
DELTA_KEY = "; Sanctioned-delta:"
PLACEHOLDER_KEY = "; Placeholder:"


def parse(text: str) -> dict:
    out = {"source": None, "sanctioned": set(), "placeholder": None, "malformed": []}
    for line in text.splitlines():
        # Header keys are LEADING '; ' comments only. A resource body string that happens
        # to contain "; Source:" is data, not a declaration.
        if not line.startswith("; "):
            continue
        if line.startswith(SOURCE_KEY):
            value = line[len(SOURCE_KEY):].strip()
            if value:
                out["source"] = value
        elif line.startswith(PLACEHOLDER_KEY):
            out["placeholder"] = line[len(PLACEHOLDER_KEY):].strip() or None
        elif line.startswith(DELTA_KEY):
            body = line[len(DELTA_KEY):].strip()
            if body.lower() == "none" or not body:
                continue
            for clause in body.split(";"):
                clause = clause.strip()
                if not clause:
                    continue
                # "<field> <from>→<to>, <reason>". The comma is what carries the reason,
                # and the reason is what makes the exemption a recorded decision.
                head, sep, reason = clause.partition(",")
                field = head.split()[0] if head.split() else ""
                if sep and reason.strip() and field:
                    out["sanctioned"].add(field)
                else:
                    out["malformed"].append(
                        f"Sanctioned-delta {clause!r} has no reason after a comma; "
                        f"no exemption granted")
    return out


def write_source(path: Path, source: str) -> bool:
    """Insert a `; Source:` line into a .tres header. False when one is already there."""
    text = path.read_text()
    if parse(text)["source"] is not None:
        return False
    lines = text.splitlines(keepends=True)
    # After the last leading header comment, so it joins the existing block rather than
    # displacing the title line.
    insert_at = 0
    for i, line in enumerate(lines):
        if line.startswith("; "):
            insert_at = i + 1
        else:
            break
    lines.insert(insert_at, f"; Source: {source}\n")
    path.write_text("".join(lines))
    return True


def selftest_cases(c) -> None:
    src = "source-content/assets/Farm Animals by @Quaternius/Blends/Sheep.blend"
    good = (f"; Sheep — generated by scripts/asset_pipeline.py run 20260830-sheep-5652\n"
            f"; Source: {src}\n"
            f"; Sanctioned-delta: none\n"
            f"[gd_resource type=\"Resource\"]\n")
    d = parse(good)
    c.eq(d["source"], src, "Source path parsed")
    c.eq(d["sanctioned"], set(), "'none' sanctions nothing")
    c.eq(d["placeholder"], None, "no Placeholder key means not a placeholder")
    c.eq(d["malformed"], [], "a well-formed header reports nothing malformed")

    c.eq(parse("[gd_resource]\n")["source"], None, "absent Source is None")

    with_reason = "; Sanctioned-delta: materials 7→5, look pass merged duplicates\n"
    c.eq(parse(with_reason)["sanctioned"], {"materials"},
         "a delta WITH a reason exempts its field")

    no_reason = "; Sanctioned-delta: materials 7→5\n"
    c.eq(parse(no_reason)["sanctioned"], set(),
         "a delta with NO reason grants no exemption")
    c.check(parse(no_reason)["malformed"],
            "a reasonless delta is reported as malformed, not silently ignored")

    two = "; Sanctioned-delta: materials 7→5, merged; vertices 10x, LOD baked in\n"
    c.eq(parse(two)["sanctioned"], {"materials", "vertices"},
         "semicolon separates multiple deltas")

    ph = "; Placeholder: grey-box, no source art yet\n"
    c.eq(parse(ph)["placeholder"], "grey-box, no source art yet",
         "Placeholder reason captured verbatim")

    # A header comment must not be confused with resource body text.
    c.eq(parse("id = \"; Source: not-a-header\"\n")["source"], None,
         "only leading '; ' lines are header keys")
