"""The `.tres` header contract the fidelity audit reads.

The audit compares runtime against source MODULO what the artifact itself declares, which
keeps the reason for an exemption next to the thing it excuses rather than in a script
constant. Same principle as the pipeline's `auto_accepted` stamp: the artifact states what
was decided about it.
"""

from pathlib import Path

SOURCE_KEY = "; Source:"
DELTA_KEY = "; Sanctioned-delta:"
PLACEHOLDER_KEY = "; Placeholder:"


def parse(text: str) -> dict:
    out = {"source": None, "sanctioned": set(), "placeholder": None, "malformed": []}
    for line in text.splitlines():
        # Header keys are LEADING '; ' comments only. The first line that is not a
        # '; ' comment ends the header block -- scanning stops there so a later line
        # that happens to start with "; Source:" (e.g. inside a resource body string)
        # is never read as a declaration.
        if not line.startswith("; "):
            break
        if line.startswith(SOURCE_KEY):
            value = line[len(SOURCE_KEY):].strip()
            if value:
                out["source"] = value
        elif line.startswith(PLACEHOLDER_KEY):
            out["placeholder"] = line[len(PLACEHOLDER_KEY):].strip() or None
        elif line.startswith(DELTA_KEY):
            body = line[len(DELTA_KEY):].strip()
            if body.lower() == "none" or not body:
                continue
            for clause in body.split(";"):
                clause = clause.strip()
                if not clause:
                    continue
                # "<field> <from>→<to>, <reason>". The comma is what carries the reason,
                # and the reason is what makes the exemption a recorded decision.
                head, sep, reason = clause.partition(",")
                field = head.split()[0] if head.split() else ""
                if sep and reason.strip() and field:
                    out["sanctioned"].add(field)
                else:
                    out["malformed"].append(
                        f"Sanctioned-delta {clause!r} has no reason after a comma; "
                        f"no exemption granted")
    return out


def write_source(path: Path, source: str) -> bool:
    """Insert a `; Source:` line into a .tres header. False when one is already there."""
    text = path.read_text()
    if parse(text)["source"] is not None:
        return False
    lines = text.splitlines(keepends=True)
    # After the last leading header comment, so it joins the existing block rather than
    # displacing the title line.
    insert_at = 0
    for i, line in enumerate(lines):
        if line.startswith("; "):
            insert_at = i + 1
        else:
            break
    lines.insert(insert_at, f"; Source: {source}\n")
    path.write_text("".join(lines))
    return True


def selftest_cases(c) -> None:
    import tempfile

    with tempfile.TemporaryDirectory() as td:
        d = Path(td)

        # A file with a leading "; " comment block and no Source line: the new line
        # lands INSIDE that block, not above the title line and not after the
        # resource body starts. Assert the full expected text, not just presence.
        with_block = d / "with_block.tres"
        with_block.write_text(
            '; Sheep — generated by scripts/asset_pipeline.py run 20260830-sheep-5652\n'
            '; Sanctioned-delta: none\n'
            '[gd_resource type="Resource"]\n'
            'content = "value"\n'
        )
        ok = write_source(with_block, "source-content/assets/Sheep.blend")
        c.check(ok, "write_source reports success when it inserts a Source line")
        c.eq(with_block.read_text(),
             '; Sheep — generated by scripts/asset_pipeline.py run 20260830-sheep-5652\n'
             '; Sanctioned-delta: none\n'
             '; Source: source-content/assets/Sheep.blend\n'
             '[gd_resource type="Resource"]\n'
             'content = "value"\n',
             "Source line is inserted inside the leading comment block, and every "
             "other byte of the file is unchanged")

        # A file that already declares a Source: no-op, byte-for-byte unmodified.
        already = d / "already.tres"
        original = ('; Source: source-content/assets/Existing.blend\n'
                    '[gd_resource type="Resource"]\n')
        already.write_text(original)
        ok2 = write_source(already, "source-content/assets/Other.blend")
        c.check(not ok2, "write_source returns False when a Source is already declared")
        c.eq(already.read_text(), original,
             "a file with an existing Source is left byte-for-byte unmodified")

        # A file with NO leading comment block at all: the Source line becomes the
        # leading comment itself, inserted at the very top -- sane, not corrupting
        # the first (resource) line.
        no_block = d / "no_block.tres"
        no_block.write_text('[gd_resource type="Resource"]\n')
        ok3 = write_source(no_block, "source-content/assets/Bare.blend")
        c.check(ok3, "write_source succeeds even with no leading comment block")
        c.eq(no_block.read_text(),
             '; Source: source-content/assets/Bare.blend\n'
             '[gd_resource type="Resource"]\n',
             "with no leading comment block, the Source line is inserted at the top "
             "rather than corrupting the resource line")

        # A file with no trailing newline: the last line must not be mangled.
        no_nl = d / "no_nl.tres"
        no_nl.write_text('; Header\n[gd_resource type="Resource"]')
        ok4 = write_source(no_nl, "source-content/assets/NoNewline.blend")
        c.check(ok4, "write_source succeeds on a file with no trailing newline")
        c.eq(no_nl.read_text(),
             '; Header\n; Source: source-content/assets/NoNewline.blend\n'
             '[gd_resource type="Resource"]',
             "a file with no trailing newline keeps its last line exactly as-is")

    src = "source-content/assets/Farm Animals by @Quaternius/Blends/Sheep.blend"
    good = (f"; Sheep — generated by scripts/asset_pipeline.py run 20260830-sheep-5652\n"
            f"; Source: {src}\n"
            f"; Sanctioned-delta: none\n"
            f"[gd_resource type=\"Resource\"]\n")
    d = parse(good)
    c.eq(d["source"], src, "Source path parsed")
    c.eq(d["sanctioned"], set(), "'none' sanctions nothing")
    c.eq(d["placeholder"], None, "no Placeholder key means not a placeholder")
    c.eq(d["malformed"], [], "a well-formed header reports nothing malformed")

    c.eq(parse("[gd_resource]\n")["source"], None, "absent Source is None")

    with_reason = "; Sanctioned-delta: materials 7→5, look pass merged duplicates\n"
    c.eq(parse(with_reason)["sanctioned"], {"materials"},
         "a delta WITH a reason exempts its field")

    no_reason = "; Sanctioned-delta: materials 7→5\n"
    c.eq(parse(no_reason)["sanctioned"], set(),
         "a delta with NO reason grants no exemption")
    c.check(parse(no_reason)["malformed"],
            "a reasonless delta is reported as malformed, not silently ignored")

    two = "; Sanctioned-delta: materials 7→5, merged; vertices 10x, LOD baked in\n"
    c.eq(parse(two)["sanctioned"], {"materials", "vertices"},
         "semicolon separates multiple deltas")

    ph = "; Placeholder: grey-box, no source art yet\n"
    c.eq(parse(ph)["placeholder"], "grey-box, no source art yet",
         "Placeholder reason captured verbatim")

    # A header comment must not be confused with resource body text.
    c.eq(parse("id = \"; Source: not-a-header\"\n")["source"], None,
         "only leading '; ' lines are header keys")

    # The contract says header keys live in the LEADING comment block. A later line
    # that happens to start with "; Source:" -- e.g. inside a multi-line string value
    # in the resource body -- must not override (or supply) the real declaration.
    injected = ('; Source: real\n'
                '[gd_resource type="Resource"]\n'
                'content = "some body text"\n'
                '; Source: injected\n')
    c.eq(parse(injected)["source"], "real",
         "scanning stops at the end of the leading comment block, so a later "
         "'; Source:' line in the body is not parsed as a declaration")
