"""Godot headless: import, probe, generated test, credits.

--import ALWAYS runs before --script. A bare `--headless --path project --quit` is a
parse check only: it cannot resolve a newly added class_name and reports false green
(gdd.md Technical Strategy #2, scripts/run-tests.sh's own header).
"""

from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path

ANIM_PROBE = '''extends SceneTree
func _init() -> void:
\tvar packed: PackedScene = load("res://{scene}") as PackedScene
\tif packed == null:
\t\tprint("ANIM_INDEX=-1"); quit(); return
\tvar root: Node = packed.instantiate()
\tvar idx: int = -1
\tfor i in root.get_child_count():
\t\tif root.get_child(i) is AnimationPlayer:
\t\t\tidx = i
\t\t\tbreak
\tprint("ANIM_INDEX=%d" % idx)
\troot.free()
\tquit()
'''

_ANIMATED_TEST = '''extends QATestCase
## Required-animations check on the {display} model. Generated by scripts/asset_pipeline.py.

const MODEL_PATH: String = "res://assets/{category}/{name}/{display}.tscn"
const REQUIRED_CLIPS: PackedStringArray = [{required}]
const EXPECTED_CLIP_COUNT: int = {count}

func _init() -> void:
\tbegin("{display} animations")
\tvar packed: PackedScene = load(MODEL_PATH) as PackedScene
\tif not check(packed != null, "%s loads as PackedScene" % MODEL_PATH):
\t\tfinish(); return
\tvar inst: Node = packed.instantiate()
\tif not check(inst != null, "{display}.tscn instantiates"):
\t\tfinish(); return
\tvar player: AnimationPlayer = _find_animation_player(inst)
\tif not check(player != null, "model contains an AnimationPlayer"):
\t\tinst.free(); finish(); return
\tvar clips: PackedStringArray = player.get_animation_list()
\tfor required: String in REQUIRED_CLIPS:
\t\tcheck(player.has_animation(required), "required clip \\"%s\\" is present" % required)
\tcheck_eq(clips.size(), EXPECTED_CLIP_COUNT, "clip count")
\tcheck_eq(player.autoplay, "Idle", "AnimationPlayer autoplay is \\"Idle\\"")
\tinst.free()
\tfinish()

func _find_animation_player(node: Node) -> AnimationPlayer:
\tif node is AnimationPlayer:
\t\treturn node as AnimationPlayer
\tfor child: Node in node.get_children():
\t\tvar found: AnimationPlayer = _find_animation_player(child)
\t\tif found != null:
\t\t\treturn found
\treturn null
'''

_STATIC_TEST = '''extends QATestCase
## Load/instantiate check on the {display} model. Generated by scripts/asset_pipeline.py.
## Static content -- no animation assertions (asset-import-pipeline.md step 4).

const MODEL_PATH: String = "res://assets/{category}/{name}/{display}.tscn"

func _init() -> void:
\tbegin("{display} import")
\tvar packed: PackedScene = load(MODEL_PATH) as PackedScene
\tif not check(packed != null, "%s loads as PackedScene" % MODEL_PATH):
\t\tfinish(); return
\tvar inst: Node = packed.instantiate()
\tcheck(inst != null, "{display}.tscn instantiates")
\tif inst != null:
\t\tinst.free()
\tfinish()
'''


def binary(repo: Path) -> Path:
    return Path(os.environ.get(
        "GODOT_PATH", repo / "godot" / "Godot_v4.7-stable_mono_linux.x86_64"))


def import_project(tree: Path) -> str:
    proc = subprocess.run(
        [str(binary(tree)), "--headless", "--path", str(tree / "project"), "--import"],
        capture_output=True, text=True, timeout=900)
    return proc.stdout + proc.stderr


def anim_probe_text(scene: str) -> str:
    return ANIM_PROBE.format(scene=scene)


def parse_anim_index(output: str) -> int:
    match = re.search(r"ANIM_INDEX=(-?\d+)", output)
    return int(match.group(1)) if match else -1


def anim_index(tree: Path, scene_res: str) -> int:
    probe = tree / "project" / "_anim_probe.gd"
    probe.write_text(anim_probe_text(scene_res))
    try:
        proc = subprocess.run(
            [str(binary(tree)), "--headless", "--path", str(tree / "project"),
             "--script", "res://_anim_probe.gd"],
            capture_output=True, text=True, timeout=300)
        return parse_anim_index(proc.stdout + proc.stderr)
    finally:
        probe.unlink(missing_ok=True)


def import_test_text(name: str, display: str, category: str, clips: list[str],
                     required_clips: list[str] | None = None) -> str:
    """Which template to emit is the ADAPTER's decision, not the file's.

    Keying off `clips` alone would hand the animated template to a building that happens
    to carry an incidental clip (a rotating windmill blade), producing an empty
    REQUIRED_CLIPS that asserts nothing plus an `autoplay == "Idle"` check the adapter
    never asked for -- which would false-fail on legitimate static content. `anim_index`'s
    call site already keys off spec.required_clips; this matches it.
    """
    required_clips = required_clips or []
    if not required_clips:
        return _STATIC_TEST.format(name=name, display=display, category=category)
    required = ", ".join(f'"{c}"' for c in required_clips if c in clips)
    return _ANIMATED_TEST.format(name=name, display=display, category=category,
                                 required=required, count=len(clips))


def write_import_test(tree: Path, name: str, display: str, category: str,
                      clips: list[str], required_clips: list[str] | None = None) -> Path:
    path = tree / "project" / "tests" / f"test_{name}_import.gd"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(import_test_text(name, display, category, clips, required_clips))
    return path


def run_tests(tree: Path, filt: str = "") -> tuple[bool, str]:
    cmd = ["bash", "scripts/run-tests.sh"] + ([filt] if filt else [])
    proc = subprocess.run(cmd, cwd=tree, capture_output=True, text=True, timeout=1800)
    return proc.returncode == 0, proc.stdout + proc.stderr


def regenerate_credits(tree: Path) -> str:
    proc = subprocess.run(
        [str(binary(tree)), "--headless", "--path", str(tree / "project"),
         "--script", "res://attribution/generate_credits.gd"],
        capture_output=True, text=True, timeout=300)
    if proc.returncode != 0:
        raise RuntimeError(
            "generate_credits.gd failed -- it fails closed on a malformed attribution "
            f"entry, so treat this as a real defect:\n{proc.stdout}{proc.stderr}")
    return proc.stdout


def selftest_cases(c) -> None:
    # Animated adapter with clips -- the normal case
    text = import_test_text("pig", "Pig", "animals", ["Idle", "Walk", "Jump"],
                            required_clips=["Idle", "Walk"])
    c.check(text.startswith("extends QATestCase"), "generated test extends QATestCase")
    c.check('const MODEL_PATH: String = "res://assets/animals/pig/Pig.tscn"' in text,
            "model path points at the wrapper, not the raw file")
    c.check('REQUIRED_CLIPS: PackedStringArray = ["Idle", "Walk"]' in text,
            "required clips are the adapter's, not every clip found")
    c.check("EXPECTED_CLIP_COUNT: int = 3" in text, "clip count filled from the audit")
    c.check('check_eq(player.autoplay, "Idle"' in text, "autoplay asserted")

    # Static adapter with no required clips -- gets static template even with clips
    static_no_req = import_test_text("windmill", "Windmill", "buildings",
                                      clips=["Rotate", "Idle"],
                                      required_clips=[])
    c.check("AnimationPlayer" not in static_no_req,
            "static adapter with incidental clips skips AnimationPlayer assertions")
    c.check("REQUIRED_CLIPS" not in static_no_req,
            "static adapter with incidental clips omits REQUIRED_CLIPS const")
    c.check("instantiates" in static_no_req, "static adapter still asserts instantiate")

    # Static adapter with empty clips list -- backward compat, no required_clips arg
    static = import_test_text("well", "Well", "buildings", [])
    c.check("AnimationPlayer" not in static,
            "static content's test skips the AnimationPlayer assertions")
    c.check("instantiates" in static, "static content still asserts load and instantiate")

    # No required_clips specified at all -- safe default to static template
    default = import_test_text("tree", "Tree", "terrain", ["Sway"])
    c.check("AnimationPlayer" not in default,
            "unspecified required_clips defaults to static template")

    probe = anim_probe_text("assets/animals/pig/Pig.tscn")
    c.check("ANIM_INDEX=" in probe, "probe prints a parseable marker")
    c.check("res://assets/animals/pig/Pig.tscn" in probe, "probe targets the scene")

    c.eq(parse_anim_index("noise\nANIM_INDEX=1\nmore\n"), 1, "index parsed from output")
    c.eq(parse_anim_index("no marker here"), -1, "missing marker yields -1, not a crash")
