extends QATestCase
## Required-animations check on the Pig model. Generated by scripts/asset_pipeline.py.

const MODEL_PATH: String = "res://assets/animals/pig/Pig.tscn"
const REQUIRED_CLIPS: PackedStringArray = ["Idle", "Walk"]
const EXPECTED_CLIP_COUNT: int = 6

func _init() -> void:
	begin("Pig animations")
	var packed: PackedScene = load(MODEL_PATH) as PackedScene
	if not check(packed != null, "%s loads as PackedScene" % MODEL_PATH):
		finish(); return
	var inst: Node = packed.instantiate()
	if not check(inst != null, "Pig.tscn instantiates"):
		finish(); return
	var player: AnimationPlayer = _find_animation_player(inst)
	if not check(player != null, "model contains an AnimationPlayer"):
		inst.free(); finish(); return
	var clips: PackedStringArray = player.get_animation_list()
	for required: String in REQUIRED_CLIPS:
		check(player.has_animation(required), "required clip \"%s\" is present" % required)
	check_eq(clips.size(), EXPECTED_CLIP_COUNT, "clip count")
	check_eq(player.autoplay, "Idle", "AnimationPlayer autoplay is \"Idle\"")
	inst.free()
	finish()

func _find_animation_player(node: Node) -> AnimationPlayer:
	if node is AnimationPlayer:
		return node as AnimationPlayer
	for child: Node in node.get_children():
		var found: AnimationPlayer = _find_animation_player(child)
		if found != null:
			return found
	return null
