extends QATestCase
## Fidelity check: the runtime ShibaInu against the original it came from.
## Generated by scripts/content_fidelity.py -- do not hand-edit.
##
## Every SRC_ value below was extracted from the source file named in
## project/data/.../shiba_inu.tres, and is baked in as a literal so this suite's assertion
## count is fixed. Regenerate rather than edit.
##
## SRC_MATERIALS counts the UNIQUE materials the source mesh actually USES (a material
## reused across two surfaces is one material). SRC_TEXTURES lists ALBEDO textures only
## -- a normal or roughness map is deliberately outside what this comparison can see.
## Every asserted field can be exempted by a "; Sanctioned-delta:" line in the .tres
## header, which turns its assertion into a PEND rather than leaving it permanently red.
##
## Run:
##   $GODOT_PATH --headless --path project --import
##   $GODOT_PATH --headless --path project --script res://tests/test_shiba_inu_fidelity.gd

const WRAPPER: String = "res://assets/animals/shiba_inu/ShibaInu.tscn"
const SRC_MATERIALS: int = 6
const SRC_BASE_COLORS: Array = [Color(0.0064, 0.0064, 0.0064, 1.0), Color(0.0272, 0.0272, 0.0272, 1.0), Color(0.0311, 0.0183, 0.0074, 1.0), Color(0.3185, 0.1613, 0.0455, 1.0), Color(0.3644, 0.3757, 0.3315, 1.0), Color(0.8689, 0.8689, 0.8689, 1.0)]
const SRC_VERTEX_COLORS: bool = false
const SRC_TEXTURES: PackedStringArray = []
const SRC_CLIPS: PackedStringArray = ["Attack", "Death", "Eating", "Gallop", "Gallop_Jump", "Idle", "Idle_2", "Idle_2_HeadLow", "Idle_HitReact1", "Idle_HitReact2", "Jump_ToIdle", "Walk"]
const SRC_JOINTS: int = 46
const SANCTIONED: PackedStringArray = []


func _init() -> void:
	begin("ShibaInu fidelity")
	var m: Dictionary = FidelityProbe.probe(WRAPPER)
	if not check(not m.is_empty(), "%s probes" % WRAPPER):
		finish(); return

	if SANCTIONED.has("materials"):
		note_expected_pending("materials sanctioned", "declared in the .tres header")
	else:
		check_eq(m["materials"], SRC_MATERIALS, "material count matches the source")

	if SANCTIONED.has("base_colors"):
		note_expected_pending("base_colors sanctioned", "declared in the .tres header")
	else:
		check_eq(m["base_colors"].size(), SRC_BASE_COLORS.size(),
			"one base colour per source material")
		check(_colors_match(m["base_colors"]), "every source base colour survived import")

	if SANCTIONED.has("vertex_colors"):
		note_expected_pending("vertex_colors sanctioned", "declared in the .tres header")
	else:
		check_eq(m["vertex_colors"], SRC_VERTEX_COLORS,
			"vertex-colour-as-albedo matches the source")

	if SANCTIONED.has("textures"):
		note_expected_pending("textures sanctioned", "declared in the .tres header")
	else:
		check(_covers(m["textures"], SRC_TEXTURES), "every source texture arrived")

	if SANCTIONED.has("clips"):
		note_expected_pending("clips sanctioned", "declared in the .tres header")
	else:
		check(_covers(m["clips"], SRC_CLIPS), "every source clip arrived")

	if SANCTIONED.has("joints"):
		note_expected_pending("joints sanctioned", "declared in the .tres header")
	else:
		check_eq(m["joints"], SRC_JOINTS, "skeleton joint count matches the source")
	finish()


## Compares to 4dp, matching fingerprint.round4 on the Python side.
func _colors_match(actual: Array) -> bool:
	if actual.size() != SRC_BASE_COLORS.size():
		return false
	for i: int in actual.size():
		var a: Array = actual[i]
		var b: Color = SRC_BASE_COLORS[i]
		if absf(a[0] - b.r) > 0.0001 or absf(a[1] - b.g) > 0.0001:
			return false
		if absf(a[2] - b.b) > 0.0001 or absf(a[3] - b.a) > 0.0001:
			return false
	return true


func _covers(actual: Array, expected: PackedStringArray) -> bool:
	for want: String in expected:
		if not actual.has(want):
			return false
	return true
