#!/usr/bin/env python3
"""Phase 2: generate a per-asset fidelity suite from its declared source.

One suite per asset, with the source manifest baked in as const literals. Baking is what
keeps the assertion count fixed (costs.md records the defect a data-dependent count hid)
and what keeps the ~2-4s Blender extraction at generation time rather than test time.

Usage:
    python3 scripts/content_fidelity.py           # every asset with a '; Source:'
    python3 scripts/content_fidelity.py sheep     # just this one
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from assetpipe import declared, fingerprint  # noqa: E402
from content_provenance import DATA_DIRS, REPO, wrapper_res_for  # noqa: E402


def _gd_colors(colors: list) -> str:
    return ", ".join("Color(%s, %s, %s, %s)" % tuple(c) for c in colors)


def _gd_strings(items: list) -> str:
    return ", ".join('"%s"' % s for s in items)


def suite_text(ident: str, display: str, wrapper_res: str,
               src: dict, sanctioned: set) -> str:
    return f'''extends QATestCase
## Fidelity check: the runtime {display} against the original it came from.
## Generated by scripts/content_fidelity.py -- do not hand-edit.
##
## Every SRC_ value below was extracted from the source file named in
## project/data/.../{ident}.tres, and is baked in as a literal so this suite's assertion
## count is fixed. Regenerate rather than edit.
##
## Run:
##   $GODOT_PATH --headless --path project --import
##   $GODOT_PATH --headless --path project --script res://tests/test_{ident}_fidelity.gd

const WRAPPER: String = "{wrapper_res}"
const SRC_MATERIALS: int = {src["materials"]}
const SRC_BASE_COLORS: Array = [{_gd_colors(src["base_colors"])}]
const SRC_VERTEX_COLORS: bool = {"true" if src["vertex_colors"] else "false"}
const SRC_TEXTURES: PackedStringArray = [{_gd_strings(src["textures"])}]
const SRC_CLIPS: PackedStringArray = [{_gd_strings(src["clips"])}]
const SRC_JOINTS: int = {src["joints"]}
const SANCTIONED: PackedStringArray = [{_gd_strings(sorted(sanctioned))}]


func _init() -> void:
	begin("{display} fidelity")
	var m: Dictionary = FidelityProbe.probe(WRAPPER)
	if not check(not m.is_empty(), "%s probes" % WRAPPER):
		finish(); return

	if SANCTIONED.has("materials"):
		note_expected_pending("materials sanctioned", "declared in the .tres header")
	else:
		check_eq(m["materials"], SRC_MATERIALS, "material count matches the source")

	if SANCTIONED.has("base_colors"):
		note_expected_pending("base_colors sanctioned", "declared in the .tres header")
	else:
		check_eq(m["base_colors"].size(), SRC_BASE_COLORS.size(),
			"one base colour per source material")
		check(_colors_match(m["base_colors"]), "every source base colour survived import")

	if SANCTIONED.has("vertex_colors"):
		note_expected_pending("vertex_colors sanctioned", "declared in the .tres header")
	else:
		check_eq(m["vertex_colors"], SRC_VERTEX_COLORS,
			"vertex-colour-as-albedo matches the source")

	check(_covers(m["textures"], SRC_TEXTURES), "every source texture arrived")
	check(_covers(m["clips"], SRC_CLIPS), "every source clip arrived")
	check_eq(m["joints"], SRC_JOINTS, "skeleton joint count matches the source")
	finish()


## Compares to 4dp, matching fingerprint.round4 on the Python side.
func _colors_match(actual: Array) -> bool:
	if actual.size() != SRC_BASE_COLORS.size():
		return false
	for i: int in actual.size():
		var a: Array = actual[i]
		var b: Color = SRC_BASE_COLORS[i]
		if absf(a[0] - b.r) > 0.0001 or absf(a[1] - b.g) > 0.0001:
			return false
		if absf(a[2] - b.b) > 0.0001 or absf(a[3] - b.a) > 0.0001:
			return false
	return true


func _covers(actual: Array, expected: PackedStringArray) -> bool:
	for want: String in expected:
		if not actual.has(want):
			return false
	return true
'''


def write_suite(repo: Path, ident: str, display: str, wrapper_res: str,
                src: dict, sanctioned: set) -> Path:
    path = repo / "project" / "tests" / f"test_{ident}_fidelity.gd"
    path.write_text(suite_text(ident, display, wrapper_res, src, sanctioned))
    return path


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("filter", nargs="?", default="",
                    help="only assets whose id contains this")
    args = ap.parse_args(argv)

    made, skipped = [], []
    for sub in DATA_DIRS:
        for tres in sorted((REPO / "project" / "data" / sub).glob("*.tres")):
            ident = tres.stem
            if args.filter and args.filter not in ident:
                continue
            text = tres.read_text()
            decl = declared.parse(text)
            for bad in decl["malformed"]:
                print(f"  {ident}: MALFORMED {bad}")
            if decl["placeholder"]:
                skipped.append((ident, "KNOWN-PLACEHOLDER"))
                continue
            if not decl["source"]:
                skipped.append((ident, "UNKNOWN-SOURCE -- run content_provenance.py"))
                continue
            source = REPO / decl["source"]
            if not source.is_file():
                skipped.append((ident, f"declared source missing: {decl['source']}"))
                continue
            wrapper = wrapper_res_for(text)
            display = wrapper.rsplit("/", 1)[-1].removesuffix(".tscn") or ident
            src = fingerprint.manifest_for_source(source)
            path = write_suite(REPO, ident, display, wrapper, src, decl["sanctioned"])
            made.append(path.relative_to(REPO))

    for p in made:
        print(f"  generated {p}")
    for ident, why in skipped:
        print(f"  skipped   {ident}: {why}")
    print(f"\n{len(made)} suite(s) generated, {len(skipped)} skipped.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


def selftest_cases(c) -> None:
    from assetpipe.fingerprint import empty_manifest

    m = empty_manifest() | {"materials": 2,
                            "base_colors": [[0.0374, 0.0374, 0.0374, 1.0],
                                            [0.8, 0.8, 0.8, 1.0]],
                            "vertex_colors": True, "clips": ["Idle", "Walk"],
                            "joints": 31, "vertices": 1108}
    text = suite_text("sheep", "Sheep", "res://assets/animals/sheep/Sheep.tscn", m, set())

    c.check("extends QATestCase" in text, "generated suite extends QATestCase")
    c.check("const SRC_MATERIALS: int = 2" in text, "material count baked as a literal")
    c.check("Color(0.0374, 0.0374, 0.0374, 1.0)" in text, "base colours baked")
    c.check("const SRC_VERTEX_COLORS: bool = true" in text,
            "vertex-colour flag baked as GDScript true, not Python True")
    c.check('"Idle", "Walk"' in text, "clips baked")
    c.check("do not hand-edit" in text, "generated file says so")
    # A fixed assertion count is the point: no check() inside a loop over variable data.
    c.check(text.count("\tcheck") >= 6,
            f"at least six assertions written out literally, got {text.count(chr(9)+'check')}")
    c.check("for " not in text.split("func _init")[1].split("finish()")[0],
            "no loop in the assertion body -- assertion count stays fixed")

    sanctioned = suite_text("sheep", "Sheep", "res://x.tscn", m, {"vertex_colors"})
    c.check("SANCTIONED" in sanctioned and "vertex_colors" in sanctioned,
            "sanctioned fields are recorded in the suite")
