#!/usr/bin/env python3
"""Phase 2: generate a per-asset fidelity suite from its declared source.

One suite per asset, with the source manifest baked in as const literals. Baking is what
keeps the assertion count fixed (costs.md records the defect a data-dependent count hid)
and what keeps the ~2-4s Blender extraction at generation time rather than test time.

Usage:
    python3 scripts/content_fidelity.py           # every asset with a '; Source:'
    python3 scripts/content_fidelity.py sheep     # just this one
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from assetpipe import declared, fingerprint  # noqa: E402
from content_provenance import (  # noqa: E402
    DATA_DIRS, REPO, multi_model_note, wrapper_res_for)


def _gd_colors(colors: list) -> str:
    return ", ".join("Color(%s, %s, %s, %s)" % tuple(c) for c in colors)


def _gd_strings(items: list) -> str:
    return ", ".join('"%s"' % s for s in items)


def suite_text(ident: str, display: str, wrapper_res: str,
               src: dict, sanctioned: set) -> str:
    return f'''extends QATestCase
## Fidelity check: the runtime {display} against the original it came from.
## Generated by scripts/content_fidelity.py -- do not hand-edit.
##
## Every SRC_ value below was extracted from the source file named in
## project/data/.../{ident}.tres, and is baked in as a literal so this suite's assertion
## count is fixed. Regenerate rather than edit.
##
## SRC_MATERIALS counts the UNIQUE materials the source mesh actually USES (a material
## reused across two surfaces is one material). SRC_TEXTURES lists ALBEDO textures only
## -- a normal or roughness map is deliberately outside what this comparison can see.
## Every asserted field can be exempted by a "; Sanctioned-delta:" line in the .tres
## header, which turns its assertion into a PEND rather than leaving it permanently red.
##
## Run:
##   $GODOT_PATH --headless --path project --import
##   $GODOT_PATH --headless --path project --script res://tests/test_{ident}_fidelity.gd

const WRAPPER: String = "{wrapper_res}"
const SRC_MATERIALS: int = {src["materials"]}
const SRC_BASE_COLORS: Array = [{_gd_colors(src["base_colors"])}]
const SRC_VERTEX_COLORS: bool = {"true" if src["vertex_colors"] else "false"}
const SRC_TEXTURES: PackedStringArray = [{_gd_strings(src["textures"])}]
const SRC_CLIPS: PackedStringArray = [{_gd_strings(src["clips"])}]
const SRC_JOINTS: int = {src["joints"]}
const SANCTIONED: PackedStringArray = [{_gd_strings(sorted(sanctioned))}]


func _init() -> void:
	begin("{display} fidelity")
	var m: Dictionary = FidelityProbe.probe(WRAPPER)
	if not check(not m.is_empty(), "%s probes" % WRAPPER):
		finish(); return

	if SANCTIONED.has("materials"):
		note_expected_pending("materials sanctioned", "declared in the .tres header")
	else:
		check_eq(m["materials"], SRC_MATERIALS, "material count matches the source")

	if SANCTIONED.has("base_colors"):
		note_expected_pending("base_colors sanctioned", "declared in the .tres header")
	else:
		check_eq(m["base_colors"].size(), SRC_BASE_COLORS.size(),
			"one base colour per source material")
		check(_colors_match(m["base_colors"]), "every source base colour survived import")

	if SANCTIONED.has("vertex_colors"):
		note_expected_pending("vertex_colors sanctioned", "declared in the .tres header")
	else:
		check_eq(m["vertex_colors"], SRC_VERTEX_COLORS,
			"vertex-colour-as-albedo matches the source")

	if SANCTIONED.has("textures"):
		note_expected_pending("textures sanctioned", "declared in the .tres header")
	else:
		check(_covers(m["textures"], SRC_TEXTURES), "every source texture arrived")

	if SANCTIONED.has("clips"):
		note_expected_pending("clips sanctioned", "declared in the .tres header")
	else:
		check(_covers(m["clips"], SRC_CLIPS), "every source clip arrived")

	if SANCTIONED.has("joints"):
		note_expected_pending("joints sanctioned", "declared in the .tres header")
	else:
		check_eq(m["joints"], SRC_JOINTS, "skeleton joint count matches the source")
	finish()


## Compares to 4dp, matching fingerprint.round4 on the Python side.
func _colors_match(actual: Array) -> bool:
	if actual.size() != SRC_BASE_COLORS.size():
		return false
	for i: int in actual.size():
		var a: Array = actual[i]
		var b: Color = SRC_BASE_COLORS[i]
		if absf(a[0] - b.r) > 0.0001 or absf(a[1] - b.g) > 0.0001:
			return false
		if absf(a[2] - b.b) > 0.0001 or absf(a[3] - b.a) > 0.0001:
			return false
	return true


func _covers(actual: Array, expected: PackedStringArray) -> bool:
	for want: String in expected:
		if not actual.has(want):
			return false
	return true
'''


def write_suite(repo: Path, ident: str, display: str, wrapper_res: str,
                src: dict, sanctioned: set) -> Path:
    path = repo / "project" / "tests" / f"test_{ident}_fidelity.gd"
    path.write_text(suite_text(ident, display, wrapper_res, src, sanctioned))
    return path


# States in which an asset was ACTUALLY compared against its source. Everything else is
# a reason no comparison happened -- see _summary().
COMPARED_STATES = ("OK", "WARN", "FAIL")


def _format_row(ident: str, state: str, findings: list, note: str = "") -> str:
    head = f"  {ident:<20} {state}"
    if findings:
        detail = "; ".join(f"{f.field} [{f.level}] {f.detail}" for f in findings)
        return f"{head}  {detail}"
    if note:
        return f"{head}  {note}"
    return head


def _exit_code(verdicts: list) -> int:
    """Warnings never fail the command -- the bands they use are unruled proposals."""
    return 1 if any(v == "FAIL" for v in verdicts) else 0


def _summary(rows: list) -> list:
    """The summary block, as lines.

    The count that matters is how many assets were NOT compared at all. A run that says
    "0 FAIL" while two thirds of the content carries no source is a green light nobody
    earned, and run-tests.sh's "114 passed" says nothing about it either. So the
    unverified total is stated first, loudly, and broken down by reason.
    """
    counts: dict = {}
    for row in rows:
        counts[row[1]] = counts.get(row[1], 0) + 1
    compared = sum(v for k, v in counts.items() if k in COMPARED_STATES)
    unverified = len(rows) - compared
    reasons = ", ".join(f"{v} {k}" for k, v in sorted(counts.items())
                        if k not in COMPARED_STATES)

    lines = [""]
    if unverified:
        lines.append(f"*** {unverified} of {len(rows)} ASSET(S) NOT VERIFIED -- no "
                     f"comparison was made against any source.")
        lines.append(f"    Reasons: {reasons}")
        lines.append("    A clean verdict list below covers the "
                     f"{compared} compared asset(s) ONLY. It is NOT a statement about "
                     "the other "
                     f"{unverified}.")
    else:
        lines.append(f"All {len(rows)} asset(s) were compared against a declared source.")
    lines.append("")
    lines.append(f"{compared} compared: "
                 + (", ".join(f"{counts[k]} {k}" for k in COMPARED_STATES if k in counts)
                    or "none"))
    if reasons:
        lines.append(f"{unverified} not compared: {reasons}")
    return lines


def report(repo: Path, filt: str = "") -> tuple:
    from content_provenance import runtime_manifest

    rows, verdicts = [], []
    for sub in DATA_DIRS:
        for tres in sorted((repo / "project" / "data" / sub).glob("*.tres")):
            ident = tres.stem
            if filt and filt not in ident:
                continue
            text = tres.read_text()
            decl = declared.parse(text)
            if decl["placeholder"]:
                rows.append((ident, "KNOWN-PLACEHOLDER", [], ""))
                verdicts.append("KNOWN-PLACEHOLDER")
                continue
            wrappers = wrapper_res_for(text)
            # MULTI-MODEL is a STATE, not a verdict: not OK, not FAIL. An asset that
            # bundles N models has no single "; Source:" to compare against, and
            # probing one of them and calling the asset OK is precisely the false
            # green this audit exists to prevent (Ruling 17).
            note = multi_model_note(wrappers)
            if note:
                rows.append((ident, "MULTI-MODEL", [], note))
                verdicts.append("MULTI-MODEL")
                continue
            if not wrappers:
                rows.append((ident, "NO-WRAPPER", [], "no PackedScene ext_resource"))
                verdicts.append("NO-WRAPPER")
                continue
            if not decl["source"]:
                rows.append((ident, "UNKNOWN-SOURCE", [], ""))
                verdicts.append("UNKNOWN-SOURCE")
                continue
            source = repo / decl["source"]
            if not source.is_file():
                rows.append((ident, "SOURCE-MISSING", [], decl["source"]))
                verdicts.append("SOURCE-MISSING")
                continue
            src = fingerprint.manifest_for_source(source)
            run = runtime_manifest(repo, wrappers[0])
            findings = fingerprint.compare(src, run, decl["sanctioned"])
            state = fingerprint.verdict(findings)
            rows.append((ident, state, findings, ""))
            verdicts.append(state)
    return rows, _exit_code(verdicts)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("filter", nargs="?", default="",
                    help="only assets whose id contains this")
    ap.add_argument("--report", action="store_true",
                    help="audit declared sources against runtime; do not generate suites")
    args = ap.parse_args(argv)

    if args.report:
        rows, code = report(REPO, args.filter)
        for ident, state, findings, note in rows:
            print(_format_row(ident, state, findings, note))
        for line in _summary(rows):
            print(line)
        return code

    made, skipped = [], []
    for sub in DATA_DIRS:
        for tres in sorted((REPO / "project" / "data" / sub).glob("*.tres")):
            ident = tres.stem
            if args.filter and args.filter not in ident:
                continue
            text = tres.read_text()
            decl = declared.parse(text)
            for bad in decl["malformed"]:
                print(f"  {ident}: MALFORMED {bad}")
            if decl["placeholder"]:
                skipped.append((ident, "KNOWN-PLACEHOLDER"))
                continue
            wrappers = wrapper_res_for(text)
            # No suite is generated for a multi-model asset. A suite bakes ONE wrapper
            # path and one source manifest; for an 18-model .tres that would assert
            # about a single arbitrary model and go green for the other 17 (Ruling 17).
            note = multi_model_note(wrappers)
            if note:
                skipped.append((ident, f"MULTI-MODEL -- {note}"))
                continue
            if not wrappers:
                skipped.append((ident, "no PackedScene ext_resource"))
                continue
            if not decl["source"]:
                skipped.append((ident, "UNKNOWN-SOURCE -- run content_provenance.py"))
                continue
            source = REPO / decl["source"]
            if not source.is_file():
                skipped.append((ident, f"declared source missing: {decl['source']}"))
                continue
            wrapper = wrappers[0]
            display = wrapper.rsplit("/", 1)[-1].removesuffix(".tscn") or ident
            src = fingerprint.manifest_for_source(source)
            path = write_suite(REPO, ident, display, wrapper, src, decl["sanctioned"])
            made.append(path.relative_to(REPO))

    for p in made:
        print(f"  generated {p}")
    for ident, why in skipped:
        print(f"  skipped   {ident}: {why}")
    print(f"\n{len(made)} suite(s) generated, {len(skipped)} skipped.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


def selftest_cases(c) -> None:
    from assetpipe.fingerprint import empty_manifest

    m = empty_manifest() | {"materials": 2,
                            "base_colors": [[0.0374, 0.0374, 0.0374, 1.0],
                                            [0.8, 0.8, 0.8, 1.0]],
                            "vertex_colors": True, "clips": ["Idle", "Walk"],
                            "joints": 31, "vertices": 1108}
    text = suite_text("sheep", "Sheep", "res://assets/animals/sheep/Sheep.tscn", m, set())

    c.check("extends QATestCase" in text, "generated suite extends QATestCase")
    c.check("const SRC_MATERIALS: int = 2" in text, "material count baked as a literal")
    c.check("Color(0.0374, 0.0374, 0.0374, 1.0)" in text, "base colours baked")
    c.check("const SRC_VERTEX_COLORS: bool = true" in text,
            "vertex-colour flag baked as GDScript true, not Python True")
    c.check('"Idle", "Walk"' in text, "clips baked")
    c.check("do not hand-edit" in text, "generated file says so")
    # A fixed assertion count is the point: no check() inside a loop over variable data.
    c.check(text.count("\tcheck") >= 6,
            f"at least six assertions written out literally, got {text.count(chr(9)+'check')}")
    c.check("for " not in text.split("func _init")[1].split("finish()")[0],
            "no loop in the assertion body -- assertion count stays fixed")

    sanctioned = suite_text("sheep", "Sheep", "res://x.tscn", m, {"vertex_colors"})
    c.check("SANCTIONED" in sanctioned and "vertex_colors" in sanctioned,
            "sanctioned fields are recorded in the suite")

    # EVERY asserted field must have a sanctioned branch. declared.parse accepts a
    # Sanctioned-delta for any field and --report honours it, so a field the generated
    # suite does not branch on is one an operator can never clear: permanently red with
    # a recorded, accepted reason sitting right there in the .tres header.
    for field in ("materials", "base_colors", "vertex_colors", "textures", "clips",
                  "joints"):
        c.check(f'SANCTIONED.has("{field}")' in text
                and f'note_expected_pending("{field} sanctioned"' in text,
                f"{field} has a sanctioned branch -- a declared delta for it turns the "
                f"assertion into a PEND instead of leaving it permanently red")

    # The branch is a RUNTIME check against the baked SANCTIONED array, so no asserted
    # field may be asserted outside one. Every `check` in the body sits under an else.
    body = text.split("func _init", 1)[1].split("\n\n\n", 1)[0]
    stray = [ln for ln in body.splitlines()
             if ln.lstrip().startswith(("check(", "check_eq("))
             and not ln.startswith("\t\t")]
    c.eq(stray, [],
         f"every field assertion sits inside its sanctioned else-branch, got {stray}")

    from assetpipe.fingerprint import Finding

    ok_row = _format_row("sheep", "OK", [])
    c.check(ok_row.strip() == "sheep                OK".replace("  ", " ").strip()
            or ok_row.split() == ["sheep", "OK"],
            f"an OK row is just the asset and its state, got {ok_row!r}")
    row = _format_row("pug", "FAIL", [Finding("materials", "FAIL", "source 2 vs runtime 1")])
    c.check("FAIL" in row and "materials" in row and "source 2 vs runtime 1" in row,
            f"a failing row carries the field and the numbers, got {row!r}")
    warn = _format_row("stag", "WARN", [Finding("vertices", "WARN", "outside band")])
    c.check("WARN" in warn and "vertices" in warn, "a warning row names its field")

    c.eq(_exit_code(["OK", "WARN", "OK"]), 0, "warnings alone exit 0")
    c.eq(_exit_code(["OK", "FAIL"]), 1, "any FAIL exits 1")
    c.eq(_exit_code(["KNOWN-PLACEHOLDER", "UNKNOWN-SOURCE"]), 0,
         "declared placeholders and unknown sources are states, not failures")
    c.eq(_exit_code([]), 0, "nothing to check exits 0")
    c.eq(_exit_code(["MULTI-MODEL", "NO-WRAPPER"]), 0,
         "MULTI-MODEL is a state, not a verdict -- it neither passes nor fails the run")

    # --- the unverified count must be impossible to miss ----------------------------
    # 19 of 31 assets carried no source while run-tests.sh printed "114 passed". A
    # summary that only lists verdicts lets a green report read as "all content
    # verified", which is the one claim this tool must never make falsely.
    mixed = [("a", "OK", [], ""), ("b", "WARN", [], ""),
             ("c", "UNKNOWN-SOURCE", [], ""), ("d", "UNKNOWN-SOURCE", [], ""),
             ("e", "MULTI-MODEL", [], "18 model wrappers")]
    text_summary = "\n".join(_summary(mixed))
    c.check("3 of 5 ASSET(S) NOT VERIFIED" in text_summary,
            f"the summary leads with the unverified count, got:\n{text_summary}")
    c.check("2 UNKNOWN-SOURCE" in text_summary and "1 MULTI-MODEL" in text_summary,
            "the unverified count is broken down by reason")
    c.check("2 compared" in text_summary,
            "the summary states how many assets were actually compared")
    c.check("NOT a statement about the other 3" in text_summary,
            "the summary explicitly refuses to let a clean verdict list stand in for "
            "the assets it did not check")

    clean = [("a", "OK", [], ""), ("b", "OK", [], "")]
    clean_summary = "\n".join(_summary(clean))
    c.check("NOT VERIFIED" not in clean_summary
            and "All 2 asset(s) were compared" in clean_summary,
            f"with nothing unverified the warning is absent, got:\n{clean_summary}")

    c.check("18 model wrappers" in _format_row("human", "MULTI-MODEL", [],
                                               "18 model wrappers"),
            "a MULTI-MODEL row carries the reason it got no verdict")
